# Generated by Django 4.2.7 on 2024-02-13 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("title", "chapter")},
        ),
    ]
