# Generated by Django 4.2.7 on 2024-02-13 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0003_course_buyers_course_cert_users_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="updatet_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="chapter",
            old_name="updatet_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="updatet_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="updatet_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="updatet_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="course",
            name="buyers",
            field=models.ManyToManyField(blank=True, related_name="buy_courses", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="course",
            name="cert_users",
            field=models.ManyToManyField(blank=True, related_name="certificated_courses", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="course",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="like_courses", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="finished_users",
            field=models.ManyToManyField(blank=True, related_name="finished_lessons", to=settings.AUTH_USER_MODEL),
        ),
    ]
